pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: webhook-dev

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - CON_NAME=$(docker run -d --rm webhook-dev -verbose -nopanic)
      - timeout -t 10 /bin/sh -xc
            "docker logs --tail=all -f $$CON_NAME 2>&1
                | tee /dev/stderr
                | while read line; do
                    if grep -qm 1 'serving hooks'; then
                        docker kill $$CON_NAME;
                        exit 0;
                    fi;
                  done" || { docker kill $$CON_NAME; exit 37; }

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: webhook-dev
    repo: spritsail/webhook

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
